# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
#
#
$background = rgb(1e1e1f)
$color1 = rgb(a17efc)
$color2 = rgb(75bfff)
$color3 = rgb(b3dbff)
$color4 = rgb(b294ff)
$color5 = rgb(75bfff)
$color6 = rgb(c5adff)
$color7 = rgb(97959d)
$color8 = rgb(5e5c60)
$color9 = rgb(8ac8ff)
$color10 = rgb(2b2b2c)
$color11 = rgb(515053)
$color12 = rgb(6a686e)
$color13 = rgb(e5dbff)
$color14 = rgb(69b5f7)
$foreground = rgb(f4f0ff)
