# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDECEE
background         #010005
cursor             #AB9CA5

active_tab_foreground     #010005
active_tab_background     #FDECEE
inactive_tab_foreground   #FDECEE
inactive_tab_background   #010005

active_border_color   #FDECEE
inactive_border_color #010005
bell_border_color     #272331

color0      #010005
color1		#272331
color2		#433945
color3		#715D66
color4		#65658B
color5		#B29093
color6		#BC989A
color7		#F4DCDE
color8		#AB9A9B
color9		#342F42
color10		#594C5C
color11		#977D87
color12		#8787B9
color13		#EEC0C4
color14		#FACACD
color15		#F4DCDE
